### ISSUE TITLE
Wrong type for a few ids: should be hid_t instead of int - fails with hdf5-1.10

### ISSUE THREAD

**Issue by pini-gh** [mateidavid/fast5#10]
Hi,

While trying fast5 with hdf5-1.10 I encountered unexpected failures reading valid HDF5 files.
I've eventually found out  that some ids aren't of the correct type. Please see the attached patch.

Thanks.
[hid_t.txt](https://github.com/mateidavid/fast5/files/376297/hid_t.txt)

**Comment by mateidavid** [comment]
I applied this to `dev`, I'll switch over soon. Thanks!
