### ISSUE TITLE
organization of header files

### ISSUE THREAD

**Issue by 0xaf1f** [mateidavid/fast5#14]
it looks like there's currently

```
fast5.hpp
hdf5_tools.hpp
fast5_version.hpp
logger.hpp
Huffman_Packer.hpp
Bit_Packer.hpp
```

In the Debian package, we have it as:

```
fast5.hpp
fast5/hdf5_tools.hpp
fast5/fast5_version.hpp
fast5/logger.hpp
fast5/Huffman_Packer.hpp
fast5/Bit_Packer.hpp
```

Would you accept a PR to make that change here? It would also help to separate the fast5 header files from those just needed by the examples.

**Comment by jts** [comment]
Sure, I'll merge that.
