### ISSUE TITLE
new release needed to support nanopolish 0.9.0

### ISSUE THREAD

**Issue by 0xaf1f** [mateidavid/fast5#19]
nanopolish 0.9.0 no longer builds with fast5 0.6.4, so would you mind tagging a new release to go along with it?

**Comment by jts** [comment]
Yes I'll do this, sorry for missing it.

**Comment by 0xaf1f** [comment]
No problem. Thanks for being so responsive

**Comment by jts** [comment]
`v0.6.5` tagged.
