### ISSUE TITLE
f5pack compession ratio is only 30-40% with r9.4 / albacore2

### ISSUE THREAD

**Issue by lpryszcz** [mateidavid/fast5#21]
Hi, in the blog [it's mentioned f5pack does 10x compression](https://simpsonlab.github.io/2017/02/27/packing_fast5/). But on our runs (r9.4, albacore 2) we only achieve ~40% compression. Is it expected? Are there any other ways of improving fast5 compression? 
`~/src/fast5/python/bin/f5pack --archive -R -o f5pack/$d reads/$d`

**Comment by jts** [comment]
When f5pack and that blog post was written the fast5 files contained much more information (events annotated by the basecaller). This is no longer the case so the compression ratio will be lower.

Note f5pack is an exploratory tool that we don’t support, so we don’t suggest running it in production.

Jared

**Comment by lpryszcz** [comment]
Thanks for clarification!
