### ISSUE TITLE
Error in HDF5 (1.9.220) 

### ISSUE THREAD

**Issue by nicolaprezza** [mateidavid/fast5#3]
Hi!

I am very interested in this library, but I cannot make it work: if I compile and run the example a.cpp on a sample fast5 file, I obtain the error:

file_version=1
HDF5-DIAG: Error detected in HDF5 (1.9.220) thread 0:
  #000: H5T.c line 2028 in H5Tis_variable_str(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
terminate called after throwing an instance of 'hdf5_tools::Exception'
  what():  /Analyses/Basecall_2D_000/version: error in H5Tis_variable_str
Aborted (core dumped)

do you have any idea of what is going wrong here? it seems a format error, but I don't understand where it may come from. Thank you!

**Comment by nicolaprezza** [comment]
update: using hdf5-1.8.16 the problem is solved. It seems to be a bug of the new release of HDF5 then..

**Comment by jts** [comment]
I think HDF5 1.8.x is the stable version right now, so we'll only support that. Once 1.9.x becomes the official release we'll make sure this library is compatible.

**Comment by nicolaprezza** [comment]
great, thank you!

2015-06-12 16:00 GMT-04:00 Jared Simpson <notifications@github.com>:
