### ISSUE TITLE
Please add licensing information

### ISSUE THREAD

**Issue by afif-elghraoui** [mateidavid/fast5#7]
I was looking to package nanopolish for Debian, but it depends on this project, which doesn't have any licensing information. We cannot redistribute it without knowing your licensing terms and if they comply with the Debian Free Software Guidelines.

**Comment by jts** [comment]
@afif-elghraoui thanks for letting us know

@mateidavid please add the MIT license, like nanopolish

**Comment by mateidavid** [comment]
Done
